version: "3.1"

services:
  worker:
    restart: always
    image: "node:dubnium-alpine"
    user: "node"
    working_dir: /home/node/app
    command: "npm start"
    volumes:
      - ./webhook-worker:/home/node/app
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - "mongo:database"
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: "mongodb://vernemq:vernemq@database:27017/devices"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  vernemq:
    image: vernemq/vernemq
    restart: always
    links:
      - "mongo:database"
      - "worker:worker"
    ports:
      - "1883:1883"
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      #DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"

      # Authentication with MongoDB
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_MONGODB__ENABLED: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__HOST: "database"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PORT: 27017
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__LOGIN: vernemq
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PASSWORD: vernemq
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__DATABASE: devices

      # Webhooks
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WORKER1__HOOK: "on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WORKER1__ENDPOINT: "http://worker:8080/webhook"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__WORKER2__HOOK: "on_publish"
      #DOCKER_VERNEMQ_VMQ_WEBHOOKS__WORKER2__ENDPOINT: "http://worker:8080/auth"
